services:
  api:
    build: .
    ports: 
      - "${APP_PORT}:8000"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
  db:
    image: postgres:18
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - incidents-database:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

volumes:
  incidents-database: